server:
  port: 8090
  servlet:
    context-path: /notification

spring:
  application:
    name: notificationservice
  mongodb:
    uri: mongodb://root:root@192.168.0.111:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: 192.168.0.111:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: ${SENDINBLUE_API_KEY}