server:
  port: 8888

app:
  api-prefix: /api/v1
  services:
    identity: ${IDENTITY_SERVICE_URL:http://localhost:8088}/identity

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8088}
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8089}
              predicates:
                - Path=${app.api-prefix}/profile/users/**
              filters:
                - StripPrefix=2
            - id: notification_service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8090}
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
            - id: post_service
              uri: ${POST_SERVICE_URL:http://localhost:8091}
              predicates:
                - Path=${app.api-prefix}/post/**
              filters:
                - StripPrefix=2
            - id: file_service
              uri: ${FILE_SERVICE_URL:http://localhost:8092}
              predicates:
                - Path=${app.api-prefix}/file/**
              filters:
                - StripPrefix=2
            - id: chat_service
              uri: ${CHAT_SERVICE_URL:http://localhost:8093}
              predicates:
                - Path=${app.api-prefix}/chat/**
              filters:
                - StripPrefix=2
            - id: search_service
              uri: ${SEARCH_SERVICE_URL:http://localhost:8095}
              predicates:
                - Path=${app.api-prefix}/search/**
              filters:
                - StripPrefix=2

