server:
  port: 8095
  servlet:
    context-path: /search

spring:
  application:
    name: search-service

  elasticsearch:
    Uris: http://${INFRA_HOST:localhost}:9200

  kafka:
    bootstrap-servers: ${INFRA_HOST:localhost}:9094
    consumer:
      group-id: search-group
      auto-offset-reset: earliest

jwt:
  signerKey: ${JWT_SIGNER_KEY}
