server:
  port: 8092
  servlet:
    context-path: /file

spring:
  application:
    name: file-service
  mongodb:
    uri: mongodb://root:${MONGO_PASSWORD:root}@${INFRA_HOST:localhost}:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  file:
    storage-dir: ${FILE_STORAGE_DIR:./upload}
    download-prefix: ${FILE_DOWNLOAD_PREFIX:http://localhost:8888/api/v1/file/media/download/}
