server:
  port: 8089
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://192.168.0.111:7687
    authentication:
      username: neo4j
      password: spring+neo4j
  kafka:
    bootstrap-servers: 192.168.0.111:9094

app:
  services:
    file: http://localhost:8092