server:
  port: 8093
  servlet:
    context-path: /chat
spring:
  application:
    name: chat-service
  mongodb:
    uri: mongodb://root:${MONGO_PASSWORD:root}@${INFRA_HOST:localhost}:27017/chat-service?authSource=admin
    auto-index-creation: true

app:
  services:
    profile:
      url: http://localhost:8089/profile
    identity:
      url: http://localhost:8088/identity